### ISSUE TITLE
Zephyr docs minor mistake

### ISSUE THREAD

**Issue by magnmaeh** [lf-lang/lf-lang.github.io#239] opened 2024-03-04 16:01 UTC
https://www.lf-lang.org/docs/embedded/zephyr/?target=c#hello-world

The docs say these commands are possible, but they fail:

```
cd apps/HelloWorld
lfc src/HelloWorld.lf -n
west build src-gen/HelloWorld -t run
```

The reason they fail is that the prj.conf is not copied int the src-gen directory. west build then complains about this.

**Comment by magnmaeh** [comment] 2024-03-07 13:21
This is the file structure it generates from running `lfc src/Helloworld.lf -n`. The `prj_lf.conf` file is generated, but it looks like `west build` expects `prj.conf`. Note that there is a `prj.conf`, but it is not inside the `src-gen` folder.

![image](https://github.com/lf-lang/lf-lang.github.io/assets/42750865/991f1ad4-edec-47bf-8e56-63416ad3b36a)

A solution could be to add a manual copy command, like so:

```
cd apps/HelloWorld
lfc src/HelloWorld.lf -n
cp prj.conf src-gen/HelloWorld
west build src-gen/HelloWorld -t run
```

Then it works just fine :)

**Comment by erlingrj** [comment] 2024-10-29 01:58
Closing this as I am not able to reproduce it. On my end it compiles find with `west build -b qemu_cortex_m3`

**Closed by erlingrj** 2024-10-29 01:58 UTC
Labels: documentation
